on: [pull_request]
jobs:
  auto_test:
    name: Auto Test nanoRelation Server
    runs-on: ubuntu-latest

    steps:
    - name: Git checkout
      uses: actions/checkout@v4

    - name: setup python
      uses: actions/setup-python@v5.1.1
      with:
        python-version: '3.11.5'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Start MongoDB
      uses: supercharge/mongodb-github-action@1.3.0
      with:
        mongodb-version: ${{ matrix.mongodb-version }}
        mongodb-replica-set: replset
    
    - name: Run tests
      run: |
        cd server
        python -m pytest tests/
